### ISSUE TITLE
error in docker-compose.yml

### ISSUE THREAD

**Issue by fathzer** [vegasbrianc/docker-compose-demo#4]
Hi,
Thanks for this wonderful example :-)
Unfortunately, I think there's a mistake in the docker-compose.yml file that prevents your demo from running on a remote docker machine.
In the web section, the following lines overrides the app.py you add in DockerFile and make the image fail if app.py is not deployed on the host machine.

```
  volumes:
   - .:/code

```

Best regards,
Jean-Marc Astesana

**Comment by vegasbrianc** [comment]
Hi @fathzer thanks for the comment. Are you using Swarm or how are you managing the remote server? Unfortunately, this demo was only intended to run locally but I will have a look to see how to fix it.

Brian

**Comment by fathzer** [comment]
Hi Brian,
I use a single remote machine created with docker-machine create (not a swarm cluster).
Your demo works well in this context if you remove the lines mentioned above.
As the app is already included in the built web container, there's no need to share volume between the host and that container.
Best regards,
Jean-Marc Astesana
PS: I hope I'm clear. I don't speak English very well.

**Comment by vegasbrianc** [comment]
I added a new section which includes the version 2 compose file format and accompanying docker-compose-v2.yml file. This may fix your issue as well. - [version 2 compose](https://github.com/vegasbrianc/docker-compose-demo/blob/master/README.md#version-2-compose-file)

New compose file - [compose file](https://github.com/vegasbrianc/docker-compose-demo/blob/master/docker-compose-v2.yml)
