### ISSUE TITLE
How would this work with docker stack deploy now, since networking is different

### ISSUE THREAD

**Issue by ashkakan** [vegasbrianc/docker-compose-demo#7]
hey, 
How would the front-tier and back-tier netwroking go with the docker stack deploy, how would you use the overlay drivers etc to make the same port mapping happen?

**Comment by vegasbrianc** [comment]
Hi @ashkakan Thanks for your comment. I recommend you take a look at my other monitoring stack as it use stack deploy and utilizes all the network functionality https://github.com/vegasbrianc/prometheus

If you have any questions let me know.
